version: "3.8"
services:
    zoo-keeper:
        image: zoo-keeper:${TAG:-latest}
        working_dir: /opt
        ports: 
            - "2181:2181"
        stdin_open: true
        tty: true
    kafka-broker:
        image: kafka-broker:${TAG:-latest}
        depends_on: 
            - "zoo-keeper"
        stdin_open: true
        tty: true
        working_dir: /opt
        ports: 
            - "9092:9092"
        volumes: 
            - ./configs:/opt/configs

